version: "3"
services:
  app:
    container_name: test-task-for-exadel
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: '8080'
      MONGODB_HOST: "mongo"
      MONGODB_PORT: "27017"
      MONGODB_USER: "user"
      MONGODB_PASS: "pass"
      MONGODB_DB: "analytics"
      MONGODB_COLLECTION: "series_access"
      MEMCACHED_HOST: "cache"
      MEMCACHED_PORT: "11211"
    links:
      - mongo
      - cache
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
  cache:
    container_name: cache
    image: memcached
    ports:
      - "11211:11211"

volumes:
  mongo-data:
    external: false
